# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['posted_on'],
            },
        ),
        migrations.CreateModel(
            name='EngineRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=40)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Trade Car View Customer Center Kenya', 'Trade Car View Customer Center Kenya,Nairobi'), ('Auto Assistant', 'Auto Assistant,Nairobi'), ('Toyota Kenya', 'Toyota Kenya,Nairobi'), ('Toyotsu Kenya', 'Toyotsu Kenya,Nairobi'), ('Motorshop.co.ke', 'Motorshop.co.ke,Nairobi'), ('Toyopet Automobiles K LTD', 'Toyopet Automobiles K LTD,Mombasa'), ('Sabaki Commercial Agencies', 'Sabaki Commercial Agencies,Mombasa'), ('Al- Husain Motors Ltd', 'Al- Husain Motors Ltd,Mombasa'), ('Osaka Motors Limited', 'Osaka Motors Limited,Mombasa'), ('Fahari Cars Limited', 'Fahari Cars Limited,Mombasa'), ('Ukerio Motors', 'Ukerio Motors,Eldoret'), ('Sagoo’s Garage Limited', 'Sagoo’s Garage Limited,Eldoret'), ('Trans Africa Motors Limited', 'Trans Africa Motors Limited,Eldoret')], max_length=150)),
                ('description', models.TextField()),
                ('engine_type', models.TextField()),
                ('engine_rating', models.TextField(blank=True, null=True)),
                ('engine_power', models.TextField()),
                ('rating', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='carapp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bio', models.TextField()),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsabilityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='who_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Make'),
        ),
        migrations.AddField(
            model_name='image',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.Model'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enginerating',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Image'),
        ),
        migrations.AddField(
            model_name='enginerating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='carapp.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodyrating',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Image'),
        ),
        migrations.AddField(
            model_name='bodyrating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.Profile'),
        ),
    ]
