# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Make',
            new_name='Rider',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='model',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='make',
            new_name='rider',
        ),
    ]
