# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20190110_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='image',
            name='engine_rating',
        ),
        migrations.RemoveField(
            model_name='image',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='rating',
        ),
    ]
